# Generated by Django 5.1.1 on 2024-09-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showsbooking', '0003_booking_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_id',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
