# Generated by Django 5.1.1 on 2024-09-16 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showsbooking', '0004_booking_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_id',
        ),
    ]
