# Generated by Django 5.1.1 on 2024-09-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('category', models.CharField(choices=[('Diamond', 'Diamond'), ('Gold', 'Gold'), ('Silver', 'Silver')])),
            ],
        ),
    ]
