# Generated by Django 5.1.1 on 2024-09-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_alter_shows_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='seats_booked',
            field=models.IntegerField(default=0),
        ),
    ]
