# Generated by Django 5.1.1 on 2024-09-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('genre', models.CharField(max_length=20)),
                ('language', models.CharField(choices=[('English', 'English'), ('Urdu', 'Urdu')])),
                ('movie_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('release_date', models.DateField()),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
